vim.g.mapleader=' '

vim.api.nvim_set_keymap('n', '<C-h>', '<C-w>h', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-j>', '<C-w>j', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-k>', '<C-w>k', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-l>', '<C-w>l', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n','<leader>ff',':Telescope find_files<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>fg',':Telescope live_grep<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>gs',':Telescope git_status<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>gc',':Telescope git_commits<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>gi',':Telescope gh issues<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>gcp',':Telescope gh pull_request<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>gst',':Telescope gh gist<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>gr',':Telescope gh run<CR>',{noremap=true,silent=true})
vim.keymap.set("n", "<leader>e", ":Ex<CR>", { silent = true })
vim.api.nvim_set_keymap('n','<leader>gp',':Git Pull<CR>',{noremap=true,silent=true})
vim.api.nvim_set_keymap('n','<leader>tq',':tabclose<CR>',{noremap=true,silent=true})
vim.keymap.set('n',"<leader>r",function()
  dofile(vim.fn.stdpath("config") .. "/init.lua")
  print("Reloaded config")
end)
vim.keymap.set('n', '<leader>t', ':tabnew<Space>', { noremap = true, silent = true })
vim.keymap.set('n','<leader>gb',':Telescope git_branches<CR>',{noremap=true,silent=true})
vim.keymap.set("n", "ww", "<C-w>", { remap = true })
vim.keymap.set('n','<leader>t',':split | :term<CR>')
vim.keymap.set('n','<leader>q',':q<CR>')
vim.keymap.set('n','<leader>s',':w<CR>')
